graph:
  curve_num: 2  # 曲线的数量
  curve_names:  # 曲线的名称
    - 原曲线
    - 滤波后
    # - l3
    # - l4
    # - l5
    # - l6
  attention_range: 50 # 专注显示的范围
  curve_color: # 曲线的颜色
    - "#ff7f0e"
    - "#2ca02c"
    - "#1f77b4"
    - "#b22222"
    - "#ffff00"
    - "#ff1493"
    - "#00bfbf"
    - "#00bfff"
    - "#7fffd4"
    - "#32cd32"